## 히든레이어
* boston csv : https://raw.githubusercontent.com/Jay-Ppark/machine_learning/master/coding_everybody/tensorflow1/csv/boston.csv
* iris csv : https://raw.githubusercontent.com/Jay-Ppark/machine_learning/master/coding_everybody/tensorflow1/csv/iris.csv

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## boston

In [4]:
# 데이터 불러오기
bpath = 'https://raw.githubusercontent.com/Jay-Ppark/machine_learning/master/coding_everybody/tensorflow1/csv/boston.csv'
bdata = pd.read_csv(bpath)
print(bdata.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [6]:
# 독립변수, 종속변수
ind_bdata = bdata[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
dep_bdata = bdata[['medv']]
print(ind_bdata.shape, dep_bdata.shape)

(506, 13) (506, 1)


In [9]:
# 모델의 구조를 만듬
# H -> hidden layer
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [14]:
# 모델의 모양 해석 가능
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [13]:
# 모델을 학습
# 원래는 25가 한계였는데 multi layer로 정확도가 더 높아짐
model.fit(ind_bdata,dep_bdata,epochs=1000, verbose=0)
model.fit(ind_bdata,dep_bdata,epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 14.6269
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 14.8392
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 15.1515
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 15.8351
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 15.0571
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 14.7399
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 13.4679
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 14.2815
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 16.4444
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 13.9876


In [16]:
# 모델을 이용
print(model.predict(ind_bdata[:5]))
print(dep_bdata[:5])

[[32.020103]
 [21.535122]
 [33.418274]
 [32.698032]
 [29.522324]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 아이리스 품종 분류

In [17]:
# 데이터를 불러오기
ipath = 'https://raw.githubusercontent.com/Jay-Ppark/machine_learning/master/coding_everybody/tensorflow1/csv/iris.csv'
idata = pd.read_csv(ipath)
print(idata.shape)

(150, 5)


In [18]:
# one hot encoding
idata_enc = pd.get_dummies(idata)
print(idata_enc.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [22]:
# 종속변수, 독립변수
ind_idata = idata_enc[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dep_idata = idata_enc[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind_idata.shape, dep_idata.shape)

(150, 4) (150, 3)


In [23]:
# 모델의 구조를 만듬
# hidden layer 추가 (H)
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y=tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [25]:
# 모델을 학습
model.fit(ind_idata,dep_idata,epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6266 - accuracy: 0.9000
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5910 - accuracy: 0.8467
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5579 - accuracy: 0.8800
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5306 - accuracy: 0.8600
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5071 - accuracy: 0.8067
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4863 - accuracy: 0.8600
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4705 - accuracy: 0.8667
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4544 - accuracy: 0.9133
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4456 - accuracy: 0.8733
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4306 - accuracy: 0.9200
Epoch 11/100
5/5 [===========

In [26]:
# 모델을 이용
print(model.predict(ind_idata[0:5]))
print(dep_idata[0:5])

[[9.9998820e-01 1.1825128e-05 3.9144282e-08]
 [9.9977964e-01 2.1975474e-04 6.0507000e-07]
 [9.9996817e-01 3.1764994e-05 1.6303601e-07]
 [9.9993503e-01 6.4558379e-05 3.4856532e-07]
 [9.9999499e-01 4.9614946e-06 2.2898403e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
